WIP 623 type conv address
ConsenSys/orchestrate pull request #732
Opened 2021-11-09 13:35 UTC by amkCha

## PR description

## Fixed Issue(s)

fixes #623

2021-11-09 13:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ConsenSys/orchestrate?pullRequest=732) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ConsenSys/orchestrate?pullRequest=732) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ConsenSys/orchestrate?pullRequest=732) it.</sub>

2021-11-12 17:22 UTC, darioAnongba approved these changes

2021-11-16 15:31 UTC, ggarri requested changes

2021-11-16 15:31 UTC, ggarri commented on pkg/types/api/deploy_tx_request.go
> +	From            *ethcommon.Address             `json:"from" validate:"omitempty" example:"0x1abae27a0cbfb02945720425d3b80c7e09728534" swaggertype:"string"`
From is mandatory, why are you using pointer?

2021-11-16 15:31 UTC, ggarri commented on pkg/types/api/send_tx_request.go
> +	From            *ethcommon.Address            `json:"from" validate:"omitempty" example:"0x1abae27a0cbfb02945720425d3b80c7e097285534" swaggertype:"string"`
From is mandatory, why are you using pointer?

2021-11-16 15:31 UTC, ggarri commented on pkg/types/api/send_tx_request.go
> +	To              ethcommon.Address             `json:"to" validate:"required" example:"0x1abae27a0cbfb02945720425d3b80c7e09728534" swaggertype:"string"`
To is nit mandatory, why are you not using pointer?

2021-11-16 15:31 UTC, ggarri commented on pkg/types/entities/eth_params.go
> +	From            *ethcommon.Address    `json:"from,omitempty"  example:"0x1abae27a0cbfb02945720425d3b80c7e09728534" swaggertype:"string"`
From is mandatory, why are you using pointer?

2021-11-16 15:31 UTC, ggarri commented on pkg/types/entities/eth_params.go
> +	To              ethcommon.Address    `json:"to,omitempty" example:"0x1abae27a0cbfb02945720425d3b80c7e09728534" swaggertype:"string"`
To is not mandatory, why are you not using pointer?

2021-11-16 15:31 UTC, ggarri commented on pkg/types/entities/faucet.go
> +	CreditorAccount *ethcommon.Address
CreditorAccount is mandatory, why a pointer?

2021-11-25 07:25 UTC, ggarri approved these changes

2021-11-25 10:27 UTC, merged