Infra postgres refactor
ConsenSys/orchestrate pull request #891
Opened 2022-03-03 15:52 UTC by darioAnongba

## PR description

- Refactor postgres infra
- Removes Tx and DB interfaces
- Aggregates PrivateTxManager and Chains
- Modifies DB TXs logic
- Removes parsers
- Refactors array of pointers to simple arrays
- Removes `STORE_TYPE` ENV var
- Moves config to `cmd`

2022-03-04 06:24 UTC, ggarri commented on cmd/flags/postgres.go
> +		ApplicationName:   "api.store",
I believe the PG settings should not contain the app destination. I would suggest to attach this value one the config it is passed to the application requiring the usage of it

2022-03-04 06:26 UTC, ggarri commented on src/api/config.go
>  		Multitenancy: viper.GetBool(multitenancy.EnabledViperKey),
it should be ` vipr.GetBool()` insead, otherway we won't grab the values from the cmd params loaded in the vipr object

2022-03-04 06:28 UTC, ggarri commented on src/api/exported.go
> +	postgresClient, err := gopg.New(cfg.Postgres)
It might not be the scope of this PR but I would suggest to modify the New method to accept the a cfg instead of initializing it here.

```
func New(ctx context.Context, cfg *Config) (*app.App, error) {

```

2022-03-04 06:35 UTC, ggarri commented on src/api/store/postgres/store.go
> +		return persist(&s)
If I understand it properly, this won't work. The Agents under `s` will remain having the old client and not the new one, you would need to do instead
```
func (s PGStore) RunInTransaction(ctx context.Context, persist func(a store.DB) error) error {
	return s.client.RunInTransaction(ctx, func(dbTx postgres.Client) error {
		s2 := New(dbTx)
		return persist(s2)
	})
}
```

or better for performance enhancement
```
func (s PGStore) RunInTransaction(ctx context.Context, persist func(a store.DB) error) error {
	return s.client.RunInTransaction(ctx, func(dbTx postgres.Client) error {
		if s.client.AlreadyADbTx() {
			return persist(s)
		}
		return persist(New(dbTx))
	})
}
```

where you would need to add a Internface method to validate whether or not the dbClient is already under dbTx

2022-03-04 06:38 UTC, ggarri commented on cmd/api/migrate.go
> -			err := db.Close()
Where are you performing the close db connection now?

2022-03-04 06:42 UTC, ggarri commented on src/api/business/builder/transactions.go
>  		searchTransactions:      transactions.NewSearchTransactionsUseCase(db, getTransactionUC),
Is there any reason to inject the `db` object instead of passing the required DbAgent directly here? `db.TransactionRequest()`

2022-03-04 06:43 UTC, ggarri commented on src/api/business/use-cases/contracts/register_contract.go
> +func ParseEvents(data string) (map[string]string, error) {
this method can be private

2022-03-04 06:47 UTC, ggarri commented on src/api/store/models/transaction_request.go
> +func NewTxRequests(txRequests []TransactionRequest) []entities.TxRequest {
You forgot to migrate all the unit tests around parser implementations.

2022-03-04 06:49 UTC, ggarri commented on src/api/store/postgres/chain.go
> +		model := models.NewChain(chain)
WE should minimize the time within a DBTX, therefore I would suggest to move model crafting can happen outside of this callback

2022-03-04 06:49 UTC, ggarri commented on src/api/store/postgres/chain.go
> +		utils.CopyPtr(model.ToEntity(), chain)
Move it out of the DBTX

2022-03-04 06:50 UTC, ggarri commented on src/api/store/postgres/chain.go
> +		utils.CopyPtr(model.ToEntity(), chain)
Move it out

2022-03-04 06:52 UTC, ggarri requested changes
Additional comments:
- We lost of the code coverage around parsers
- We lost historical records on the data-agents

2022-03-07 12:12 UTC, darioAnongba commented on src/api/business/builder/transactions.go
>  		searchTransactions:      transactions.NewSearchTransactionsUseCase(db, getTransactionUC),
done like that in other Use cases, can be modified globally in a PR

2022-03-07 12:13 UTC, darioAnongba commented on src/api/business/use-cases/contracts/register_contract.go
> +func ParseEvents(data string) (map[string]string, error) {
resolved

2022-03-07 12:13 UTC, darioAnongba commented on src/api/store/models/transaction_request.go
> +func NewTxRequests(txRequests []TransactionRequest) []entities.TxRequest {
WIP

2022-03-07 12:18 UTC, darioAnongba commented on src/api/store/postgres/chain.go
> +		model := models.NewChain(chain)
resolved

2022-03-07 12:18 UTC, darioAnongba commented on src/api/store/postgres/chain.go
> +		utils.CopyPtr(model.ToEntity(), chain)
resolved

2022-03-07 12:18 UTC, darioAnongba commented on src/api/store/postgres/chain.go
> +		utils.CopyPtr(model.ToEntity(), chain)
resolved

2022-03-08 09:29 UTC, darioAnongba commented on cmd/api/migrate.go
> -			err := db.Close()
resolved

2022-03-10 06:57 UTC, ggarri approved these changes

2022-03-10 16:59 UTC, merged